export const FacialExpressions = {
    idle: {
      // Neutral expression
    },
    angry: {
      browDownLeft: 1,
      browDownRight: 1,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      jawForward: 1,
      jawLeft: 1,
      mouthShrugLower: 1,
      noseSneerLeft: 1,
      noseSneerRight: 0.42,
      eyeLookDownLeft: 0.16,
      eyeLookDownRight: 0.16,
      cheekSquintLeft: 1,
      cheekSquintRight: 1,
      mouthClose: 0.23,
      mouthFunnel: 0.63,
      mouthDimpleRight: 1,
    },
    "angry-gesture": {
      browDownLeft: 1,
      browDownRight: 1,
      eyeSquintLeft: 0.9,
      eyeSquintRight: 0.9,
      jawForward: 1,
      mouthShrugLower: 0.9,
      noseSneerLeft: 0.9,
      noseSneerRight: 0.4,
      cheekSquintLeft: 1,
      cheekSquintRight: 1,
      mouthFunnel: 0.5,
      mouthDimpleLeft: 0.5,
      mouthDimpleRight: 1,
    },
    crying: {
      mouthFrownLeft: 1,
      mouthFrownRight: 1,
      mouthShrugLower: 1,
      browInnerUp: 0.8,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      eyeLookDownLeft: 0.8,
      eyeLookDownRight: 0.8,
      cheekSquintLeft: 0.5,
      cheekSquintRight: 0.5,
      jawForward: 0.8,
    },
    happy: {
      browInnerUp: 0.2,
      eyeSquintLeft: 0.4,
      eyeSquintRight: 0.44,
      noseSneerLeft: 0.17,
      noseSneerRight: 0.14,
      mouthPressLeft: 0.61,
      mouthPressRight: 0.41,
    },
    punching: {
      jawLeft: 0.7,
      browDownLeft: 1,
      browDownRight: 1,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      jawForward: 1,
      noseSneerLeft: 0.7,
      noseSneerRight: 0.6,
      mouthFunnel: 0.5,
      mouthDimpleRight: 0.5,
    },
    rejected: {
      browInnerUp: 0.5,
      eyeSquintLeft: 0.6,
      eyeSquintRight: 0.6,
      mouthFrownLeft: 0.9,
      mouthFrownRight: 0.9,
      mouthShrugLower: 0.7,
      eyeLookDownLeft: 0.4,
      eyeLookDownRight: 0.4,
      jawForward: 0.8,
    },
    sad: {
      mouthFrownLeft: 1,
      mouthFrownRight: 1,
      mouthShrugLower: 0.78,
      browInnerUp: 0.45,
      eyeSquintLeft: 0.72,
      eyeSquintRight: 0.75,
      eyeLookDownLeft: 0.5,
      eyeLookDownRight: 0.5,
      jawForward: 1,
    },
    stomping: {
      browDownLeft: 1,
      browDownRight: 1,
      jawForward: 1,
      mouthShrugLower: 1,
      eyeSquintLeft: 0.9,
      eyeSquintRight: 0.9,
      noseSneerLeft: 0.8,
      noseSneerRight: 0.4,
      cheekSquintLeft: 1,
      cheekSquintRight: 1,
      mouthClose: 0.3,
    },
    thankful: {
      browInnerUp: 0.4,
      eyeSquintLeft: 0.3,
      eyeSquintRight: 0.3,
      noseSneerLeft: 0.1,
      noseSneerRight: 0.1,
      mouthSmileLeft: 0.4,
      mouthSmileRight: 0.4,
      cheekSquintLeft: 0.3,
      cheekSquintRight: 0.3,
    },
  };
  