export const FacialExpressions = {
    idle: {
      // Neutral expression
    },
    angry: {
        browDownLeft: 1, browDownRight: 1, browInnerUp: 0.15,
        eyeSquintLeft: 0.8, eyeSquintRight: 0.8,
        jawForward: 0.9, jawLeft: 0.3,
        noseSneerLeft: 0.7, noseSneerRight: 0.7,
        cheekSquintLeft: 0.7, cheekSquintRight: 0.7,
        mouthClose: 0.3, mouthPressLeft: 0.5, mouthPressRight: 0.5
    },
    "angry-gesture": {
      browDownLeft: 1,
      browDownRight: 1,
      eyeSquintLeft: 0.2,
      eyeSquintRight: 0.2,
      jawForward: 0.2,
      mouthShrugLower: 0.2,
      noseSneerLeft: 0,
      noseSneerRight: 0,
      cheekSquintLeft: 0,
      cheekSquintRight: 0,
      mouthFunnel: 0,
      mouthDimpleLeft: 0,
      mouthDimpleRight: 0,
    },
    crying: {
      mouthFrownLeft: 1,
      mouthFrownRight: 1,
      mouthShrugLower: 1,
      browInnerUp: 0.8,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      eyeLookDownLeft: 0.8,
      eyeLookDownRight: 0.8,
      cheekSquintLeft: 0.5,
      cheekSquintRight: 0.5,
      jawForward: 0.8,
    },
    // Improved happy expression
    happy: {
  
      browInnerUp: 0.3,
      browOuterUpLeft: 0.4,
      browOuterUpRight: 0.4,
      eyeSquintLeft: 0.6,
      eyeSquintRight: 0.6,
      cheekSquintLeft: 0.5,
      cheekSquintRight: 0.5,
      mouthSmileLeft: 0.4,
      mouthSmileRight: 0.4,
      mouthDimpleLeft: 0.2,
      mouthDimpleRight: 0.2,
      jawOpen: 0.1,
    },
    punching: {
      jawLeft: 0.7,
      browDownLeft: 1,
      browDownRight: 1,
      eyeSquintLeft: 1,
      eyeSquintRight: 1,
      jawForward: 1,
      noseSneerLeft: 0.7,
      noseSneerRight: 0.6,
      mouthFunnel: 0.5,
      mouthDimpleRight: 0.5,
    },
    rejected: {
      browInnerUp: 0.5,
      eyeSquintLeft: 0.6,
      eyeSquintRight: 0.6,
      mouthFrownLeft: 0.9,
      mouthFrownRight: 0.9,
      mouthShrugLower: 0.7,
      eyeLookDownLeft: 0.4,
      eyeLookDownRight: 0.4,
      jawForward: 0.8,
    },
    // Improved sad expression
    sad: {
      browInnerUp: 0.7,
      browOuterUpLeft: 0.2,
      browOuterUpRight: 0.2,
      eyeLookDownLeft: 0.3,
      eyeLookDownRight: 0.3,
      mouthFrownLeft: 0.7,
      mouthFrownRight: 0.7,
      mouthShrugLower: 0.5,
      mouthRollLower: 0.3,
      jawForward: 0.3,
      cheekSquintLeft: 0.2,
      cheekSquintRight: 0.2,
    },
    stomping: {
      browDownLeft: 1,
      browDownRight: 1,
      jawForward: 1,
      mouthShrugLower: 1,
      eyeSquintLeft: 0.9,
      eyeSquintRight: 0.9,
      noseSneerLeft: 0.8,
      noseSneerRight: 0.4,
      cheekSquintLeft: 1,
      cheekSquintRight: 1,
      mouthClose: 0.3,
    },
    thankful: {
      browInnerUp: 0.4,
      eyeSquintLeft: 0.3,
      eyeSquintRight: 0.3,
      noseSneerLeft: 0.1,
      noseSneerRight: 0.1,
      mouthSmileLeft: 0.4,
      mouthSmileRight: 0.4,
      cheekSquintLeft: 0.3,
      cheekSquintRight: 0.3,
    },
};